# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 259)

        # label_selectedDate yang baru
        self.label_selectedDate = QtWidgets.QLabel(Dialog)
        self.label_selectedDate.setGeometry(QtCore.QRect(10, 20, 381, 20))
        font_selected = QtGui.QFont()
        font_selected.setFamily("Montserrat")
        font_selected.setPointSize(12)
        font_selected.setBold(True)
        font_selected.setWeight(75)
        self.label_selectedDate.setFont(font_selected)
        self.label_selectedDate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_selectedDate.setObjectName("label_selectedDate")

        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 70, 381, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 120, 381, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Work")
        self.comboBox.addItem("Personal")

        self.timeEdit = QtWidgets.QTimeEdit(Dialog)
        self.timeEdit.setGeometry(QtCore.QRect(10, 170, 171, 22))
        self.timeEdit.setObjectName("timeEdit")

        self.timeEdit_2 = QtWidgets.QTimeEdit(Dialog)
        self.timeEdit_2.setGeometry(QtCore.QRect(220, 170, 171, 22))
        self.timeEdit_2.setObjectName("timeEdit_2")

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 81, 16))
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 81, 16))
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(220, 150, 81, 16))
        self.label_5.setObjectName("label_5")

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 220, 181, 23))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 220, 181, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_selectedDate.setText(_translate("Dialog", "Tanggal: -"))
        self.label_2.setText(_translate("Dialog", "Nama Kegiatan"))
        self.label_3.setText(_translate("Dialog", "Jenis Kegiatan"))
        self.label_4.setText(_translate("Dialog", "Dari"))
        self.label_5.setText(_translate("Dialog", "Sampai"))
        self.pushButton.setText(_translate("Dialog", "Batalkan"))
        self.pushButton_2.setText(_translate("Dialog", "Simpan"))
